---
##### Install zabbix-agent
  - name: ping hosts
    ping:

  - name: check OS
    debug: msg={{ansible_distribution}}-{{ansible_distribution_version}}

### Ubuntu 18.04 Bionic Beaver
  - name: download zabbix deb file fot Ubuntu 18.04
    get_url:
      url: https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
      dest: /tmp/zabbix-release_4.0-2+bionic_all.deb
    when: ansible_distribution_release == 'bionic'

  - name: install zabbix deb for Ubuntu 18.04 Xenial
    apt: deb="/tmp/zabbix-release_4.0-2+bionic_all.deb"
    when: ansible_distribution_release == 'bionic'

  - name: install zabbix-agent 4.0 Ubuntu 18.04
    apt:
      name: zabbix-agent
      state: latest
      update_cache: yes
    when: ansible_distribution_release == 'bionic'

##### enabled zabbix-agent
  - name: enable service zabbix-agent and ensure it is not masked
    systemd:
      name: zabbix-agent
      enabled: yes
      masked: no
    become: yes

##### check zabbix home dir and shell
  - name: Make sure a service is stopped
    systemd: state=stopped name=zabbix-agent
    become: yes

  - name: check zabbix home dir and shell
    user:
      name: zabbix
      shell: /bin/bash
      home: /etc/zabbix
    become: yes

##### mkdir /etc/zabbix/scripts and rights
  - name: mkdir /etc/zabbix/scripts and rights
    file:
      path: /etc/zabbix/scripts
      state: directory
      owner: zabbix
      group: zabbix
      mode: 0700
    become: yes

##### change zabbix_agentd.conf
  - name: change zabbix_agentd.conf Hostname
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      state: present
      regexp: 'Hostname=Zabbix server'
      line: "Hostname={{ ansible_hostname }}"
    become: yes
    
  - name: change zabbix_agentd.conf ServerActive
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      state: present
      regexp: 'ServerActive=127.0.0.1'
      line: 'ServerActive=192.168.122.189'
    become: yes

  - name: change zabbix_agentd.conf Server
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      state: present
      regexp: 'Server=127.0.0.1'
      line: 'Server=192.168.122.189'
    become: yes

  - name: change zabbix_agentd.conf EnableRemoteCommands
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      state: present
      regexp: '# EnableRemoteCommands=0'
      line: 'EnableRemoteCommands=1'
    become: yes

  - name: change zabbix_agentd.conf LogRemoteCommands
    lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      state: present
      regexp: '# LogRemoteCommands=0'
      line: 'LogRemoteCommands=1'

### Starting zabbix-agent
  - name: Make sure a service is started
    systemd: state=started name=zabbix-agent
    become: yes
